---
title: "Day 4 Comp Session 4"
format: html
editor: visual
---

### General Notes:

\>\>Git add "name of file" will allow you to update just one file in the list instead of "Git add ." which is going to push updates for all files

## Creating Vectors

```{r}
rain <- c(3, 5, 10.1, 6)
## Check the class in the console using the class() function

## Let's scale this vector:
rain_scaled <- 5 * rain 
```

## Matrices!

```{r}
## Let's first create a sequence
my_values <- seq(from = 1 , to = 10)

## Let's make this into a matrix. We use the function matrix(). We input the data, how many rows, and how many columns we want in the matrix. Byrow tells us if we want the data to fill in by rows or columns. The default is by columns
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)
```

```{r}
## Let's test whether we can create a matrix with data lengths that don't match the dimensions of the matrix we are trying to create
my_matrix_2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
my_matrix_2
## What we found is it works with a warning. The data will start repeating...
```

```{r}
## Let's make a matrix with a sequence directly in the matrix instead of creating the sequence first
matrixA <- matrix(data = seq(from = 2, to = 5, length = 10), 
                  nrow = 2 ,
                  ncol = 5, 
                  byrow = TRUE)

## Let's add the matrices
my_matrix + matrixA
```

## Matrix Multiplication

```{r}
## Let's create 2 matrices with data created as we create the matrix (instead of before creating the matrix)
cats <- matrix(data = c(0, 4, 5, 9), nrow = 2, ncol = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-2, 5, 9), nrow = 2, ncol = 2, byrow = TRUE)
##To multiply, we use the rdot function which is "%*%"
dogs %*% cats
```

## Leslie Matrix Example

```{r}
## Let's re-create our example from notes. We are populating the values from original formulas for eggs, larvae, and female adults. We need to first create a matrix of these values from the formulas.
insect_leslie <- matrix(data = c(0,0,600,.2,0,0,0,.08,0), 
                        nrow = 3, 
                        ncol = 3, 
                        byrow = TRUE)
insect_leslie

## We're now going to create an initial condition. We are saying there are initially 12,000 eggs, 700 larvaue, and 500 adult females
insect_y0 <- c(12000, 700, 500)

## Find the population structure for each life stage at t = 1 year. Now we can see that with the initial conditions, in year 1 we expect 300000 eggs, 2400 larvae, and 56 females
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
```

```{r}
## Find the population structure at t = 2 years. We use the values from y1 (insect_y1) to find the next year. 
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```
